services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Puerto para comunicación de aplicaciones (AMQP)
      - "15672:15672"  # Puerto para la interfaz web de administración
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge